import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import ProductProvider from "@/Context/ProductContext";
import CartProvider from "@/Context/CartContext";
import { Poppins } from 'next/font/google'
const logoFont = Poppins({
  subsets: ['latin'],
  weight: ['200','400']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={logoFont.className}>
        <CartProvider>
          <ProductProvider>
            <Navbar />
            {children}
            <Footer />
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
