import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Flamenco } from "next/font/google";
import Footer from "@/components/footer/Footer";
import ProductProvider from "@/Context/ProductContext";
import CartProvider from "@/Context/CartContext";
const flamenco = Flamenco({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={flamenco.className}>
        <CartProvider>
          <ProductProvider>
            <Navbar />
            {children}
            <Footer />
          </ProductProvider>
        </CartProvider>
      </body>
    </html>
  );
}
